astilines = [
"In both the Eucharistic",
"miracles of Asti from the",
"consecrated Host gushed",
"out real blood and there are",
"numerous documents that",
"confirm these events. In the",
"first miracle, Mons. Scipione",
"Roero had a notary act",
"drawn up and Pope Paul III",
"on November 6, 1535",
"granted a plenary indulgence",
"to anyone who visited the",
"Church of San Secondo on",
"the anniversary of the",
"miraculous event"
]
alatrilines = [
"In Alatri's Cathedral of",
"Saint Paul the Apostle is kept",
"even today the reliquary",
"of the Eucharistic miracle",
"that occurred in 1228 and",
"consisted in a fragment of",
"the Host turning into flesh.",
"A young woman, in an effort",
"to regain the love of her",
"sweetheart, consulted a",
"sorceress who ordered her",
"to steal a consecrated Host to",
"make a love potion. During",
"Mass, the young woman hid",
"a Host in a cloth. But when",
"she got home, she realized",
"that the Host had been",
"transformed into bleeding flesh.",
"This miracle has extensive",
"documentation, including",
"from Pope Gregory IX."
]